 windowrule = match:class spotify|Spotify silent, workspace special:spotify
 windowrule = match:class discord|equibop|vesktop silent, workspace special:discord
 windowrule = match:class slack silent, workspace special:slack
 windowrule = match:class whatsapp silent , workspace special:communication

