
animations {
    enabled = true

    bezier = fast, 0.8, 0, 1, 0.2

    animation = layersIn, 0.2, 2, fast, slide
    animation = layersOut, 0.2, 2, fast, slide
    animation = fadeLayers, 0.15, 2, fast

    animation = windowsIn, 0.2, 2, fast
    animation = windowsOut, 0.2, 1, fast
    animation = windowsMove, 0.2, 2, fast
    animation = workspaces, 0.2, 2, fast

    animation = specialWorkspace, 0.2, 2, fast, slidefadevert 20%

    animation = fade, 0.15, 2, fast
    animation = fadeDim, 0.15, 2, fast
    animation = border, 0.15, 2, fast
}
