animations {
    enabled = true

    # Animation curves (make them snappier with faster transitions)
    bezier = specialWorkSwitch, 0.2, 0.8, 0.5, 1
    bezier = emphasizedAccel, 0.7, 0, 1, 0.1
    bezier = emphasizedDecel, 0.2, 0.8, 0.4, 1
    bezier = standard, 0.1, 0, 0.3, 1

    # Animation configs
    animation = layersIn, 0.5, 3, emphasizedDecel, slide
    animation = layersOut, 0.5, 3, emphasizedAccel, slide
    animation = fadeLayers, 0.3, 4, standard

    animation = windowsIn, 0.5, 4, emphasizedDecel
    animation = windowsOut, 0.4, 2, emphasizedAccel
    animation = windowsMove, 0.3, 5, standard
    animation = workspaces, 0.3, 3, standard

    animation = specialWorkspace, 0.4, 3, specialWorkSwitch, slidefadevert 20%

    animation = fade, 0.3, 4, standard
    animation = fadeDim, 0.3, 4, standard
    animation = border, 0.3, 3, standard
}
