
general {
    # Run DMS + hyprlock ONLY if not already locked
    lock_cmd = pidof hyprlock || (pgrep -x dms || dms ipc call lock lock; hyprlock)

    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# Turn off screen faster if already locked
listener {
    timeout = 100
    on-timeout = pidof hyprlock && hyprctl dispatch dpms off
    on-resume = pidof hyprlock && hyprctl dispatch dpms on
}

# Auto lock after idle
listener {
    timeout = 300
    on-timeout = loginctl lock-session
    on-resume = notify-send -i $iDIR "System Unlocked!"
}

# Suspend after longer idle
listener {
    timeout = 600
    on-timeout = systemctl suspend
}
