preload = /home/dips/Pictures/wallpapers/apple-dark.jpg
wallpaper {
    monitor = eDP-1
    path = /home/dips/Pictures/wallpapers/apple-dark.jpg
    fit_mode = cover
}
wallpaper {
    monitor = HDMI-A-1
    path = /home/dips/Pictures/wallpapers/apple-dark.jpg
    fit_mode = cover
}
mode=fill
