# See https://wiki.hyprland.org/Configuring/Variables/ for more
decoration {
    rounding = 12
    blur {
        enabled = true
        size =5
        passes = 2
    }
    shadow {
        enabled = true
        range = 1
        render_power = 1
        color = rgba(1a1a1aee)
    }
}
