# Execute your favorite apps at launch


#exec-once = hyprpaper

exec-once = hypridle

exec-once = dms run
#for libadwaita gtk4 apps you can use this command:
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

#for gtk3 apps you need to install adw-gtk3 theme (in arch linux sudo pacman -S adw-gtk-theme)
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"   # for GTK3 apps
#exec-once = waybar

exec-once = [workspace special:spotify silent] spotify 
exec-once = [workspace special:discord silent] discord
exec-once = [workspace special:slack silent] slack 
