device{
  name=gxt7863:00-27c6:01e0-touchpad

  accel_profile =adaptive# flat or adaptive or blank or EMPTY means libinput’s default mode
}
input {
    kb_layout = us
  #kb_layout = us,us
  #kb_variant=colemak,
kb_options =,caps:ctrl_modifier
    numlock_by_default = false
    repeat_delay = 250
    repeat_rate = 35
sensitivity = 0 #mouse sensitivity
accel_profile =flat
follow_mouse = true
    focus_on_close = 1

    touchpad {
        natural_scroll = true
    #disable_while_typing = $touchpadDisableTyping
    #    scroll_factor = $touchpadScrollFactor
    }
}

binds {
    scroll_event_delay = 0
}
