
# ---------------------------
# Floating windows
# ---------------------------
windowrule = match:class guifetch, float yes
windowrule = match:class yad, float yes
windowrule = match:class zenity, float yes
windowrule = match:class wev, float yes
windowrule = match:class org\.gnome\.FileRoller, float yes
windowrule = match:class file-roller, float yes
windowrule = match:class blueman-manager, float yes
windowrule = match:class com\.github\.GradienceTeam\.Gradience, float yes
windowrule = match:class feh, float yes
windowrule = match:class imv, float yes
windowrule = match:class system-config-printer, float yes

# ---------------------------
# Float, resize, and center
# ---------------------------
windowrule = match:class foot, match:title nmtui, float yes, size 60% 70%, center yes
windowrule = match:class org\.gnome\.Settings, float yes, size 70% 80%, center yes
windowrule = match:class org\.pulseaudio\.pavucontrol|yad-icon-browser, float yes, size 60% 70%, center yes
windowrule = match:class nwg-displays, float yes, center yes
windowrule = match:class nwg-look, float yes, size 50% 60%, center yes

# ---------------------------
# Special workspaces
# ---------------------------
windowrule = match:class spotify silent, workspace special:spotify
windowrule = match:class discord|equibop|vesktop silent, workspace special:discord
windowrule = match:class slack silent, workspace special:slack
windowrule = match:class whatsapp silent , workspace special:communication
windowrule = match:class Todo, workspace special:todo

# ---------------------------
# Steam
# ---------------------------
windowrule = match:class steam, rounding 10
windowrule = match:class steam, match:title Friends List, float yes
windowrule = match:class steam_app_[0-9]+, immediate yes 

# ---------------------------
# ATLauncher console
# ---------------------------
windowrule = match:class com-atlauncher-App, match:title ATLauncher Console, float yes

# ---------------------------
# XWayland popups
# ---------------------------
windowrule = match:xwayland 1, match:title win[0-9]+, rounding 10
