# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# Float
windowrulev2 = float, class:guifetch
windowrulev2 = float, class:yad
windowrulev2 = float, class:zenity
windowrulev2 = float, class:wev
windowrulev2 = float, class:org\.gnome\.FileRoller
windowrulev2 = float, class:file-roller
windowrulev2 = float, class:blueman-manager
windowrulev2 = float, class:com\.github\.GradienceTeam\.Gradience
windowrulev2 = float, class:feh
windowrulev2 = float, class:imv
windowrulev2 = float, class:system-config-printer

# Float, resize and center
windowrulev2 = float, class:foot, title:nmtui
windowrulev2 = size 60% 70%, class:foot, title:nmtui
windowrulev2 = center, class:foot, title:nmtui

windowrulev2 = float, class:org\.gnome\.Settings
windowrulev2 = size 70% 80%, class:org\.gnome\.Settings
windowrulev2 = center, class:org\.gnome\.Settings

windowrulev2 = float, class:org\.pulseaudio\.pavucontrol|yad-icon-browser
windowrulev2 = size 60% 70%, class:org\.pulseaudio\.pavucontrol|yad-icon-browser
windowrulev2 = center, class:org\.pulseaudio\.pavucontrol|yad-icon-browser

windowrulev2 = float, class:nwg-displays
windowrulev2 = center, class:nwg-displays



windowrulev2 = float, class:nwg-look
windowrulev2 = size 50% 60%, class:nwg-look
windowrulev2 = center, class:nwg-look

# Special workspaces
windowrulev2 = workspace special:sysmon, class:btop
windowrulev2 = workspace special:music, class:feishin|Spotify|Supersonic
windowrulev2 = workspace special:postman, class:^(Postman)$
windowrulev2 = workspace special:music, initialTitle:Spotify( Free)?
windowrulev2 = workspace special:communication, class:discord|equibop|vesktop|whatsapp
windowrulev2 = workspace special:todo, class:Todo

# Picture-in-picture
windowrulev2 = move 100%-w-2% 100%-w-3%, title:Picture(-| )in(-| )[Pp]icture
windowrulev2 = keepaspectratio, title:Picture(-| )in(-| )[Pp]icture
windowrulev2 = float, title:Picture(-| )in(-| )[Pp]icture
windowrulev2 = pin, title:Picture(-| )in(-| )[Pp]icture

# Steam
windowrulev2 = rounding 10, class:steam
windowrulev2 = float, title:Friends List, class:steam
windowrulev2 = immediate, class:steam_app_[0-9]+
windowrulev2 = idleinhibit always, class:steam_app_[0-9]+

# ATLauncher console
windowrulev2 = float, class:com-atlauncher-App, title:ATLauncher Console

# Autodesk Fusion 360
windowrulev2 = noblur, title:Fusion360|(Marking Menu), class:fusion360\.exe

# XWayland popups
windowrulev2 = nodim, xwayland:1, title:win[0-9]+
windowrulev2 = noshadow, xwayland:1, title:win[0-9]+
windowrulev2 = rounding 10, xwayland:1, title:win[0-9]+
